version: "3"
networks:
  redes:
    name: redes
services:
  server:
    image: "nginx"
    container_name: server
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    ports:
      - 8080:80
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html"
    networks:
      - redes
